### ISSUE TITLE
Only certain people as dogs!

### ISSUE THREAD

**Issue by Godofdoggos** [MonAmiral/PlayerDogModel#1]
I was hoping to be able to make myself a dog, viewed by myself and others with mod, but i dont want the people im playing with to look like dogs or see themselves as dogs, only me. is there anyway to do this?

it also seems models only becomes dogs once either second day, or a player dies and respawns

**Comment by MonAmiral** [comment]
At the moment the mod only changes the models of the other players since you don't see yourself except with the third person mod but I'll fix that!
I also want to add an interaction which will let you turn into the dog, instead of it being automatic, so there can be a mix of humans and dog players! It should arrive in the coming days or next week!
I've also done an incredibly low amount of testing so I'll make sure to fix other issues, please report as many as you can!

**Comment by Godofdoggos** [comment]
i do wanna say there is a way to see yourself, but its not very clear; its the camera in the front type right, although it shows others as a dog pretty well, it shows u as the normal arm and legs only, on all fours. And ill make  sure to come here if i find any others!

**Comment by MonAmiral** [comment]
Oh, thanks for the info! It'll allow me to test things faster!

**Comment by Godofdoggos** [comment]
So far what ive found, when crouching legs phase through ground, when holding and item its at original hand position(maybe could move to mouth?) when models switch from player to dog seems inconsistant, for me i would always have to die and respawn for it to show up, but recently from the start of the match the dog model loads, but you still have to die for your own model to work (i assume from the camera, even though u only appear as arms and legs), everything else is just animations, but you said youve already know so no point in telling u. Anyways; i hope coding goes well!

**Comment by MonAmiral** [comment]
Please check out the 0.1.0 version! It adds an interaction in the ship to toggle the model on and off!
I haven't implemented loading yet: other players will need to toggle it off and on again when you join a server.

I haven't fixed any of the other issues yet as it's complex for me to test, and I'd like to have the full mod before I start debugging.

**Comment by Godofdoggos** [comment]
i just tried it out and its amazing, having it next to the suits and having it as a head model was brilliant, and i absolutely love the little animation of you shrinking, it is amazing and it meets all my expectations doubled! have a wonderfull day.
