### ISSUE TITLE
Issue with R2Modman

### ISSUE THREAD

**Issue by SpeedyDoggo** [MonAmiral/PlayerDogModel#10]
Hello! Friends and I were trying to transition to using the R2 mod manager, but this mod doesn't seem to work properly when using it despite using the same modlist as when run manually. With the fully updated version, it appears to fully work clientside. However, other players cannot see the model, but will see the dog player as shorter.

Full modlist includes:
(BepInEx and LC_API)
- LateCompany
- More_Emotes
- MoreCompany
- PlayerDogModel
- AlwaysHearActiveWalkies

We've tried PlayerDogModel in a few different places, but no dice. Any thoughts for solutions or additional testing?

UPDATE: My friends did some testing and discovered that the issue may be the LC_API 3.2.2 version. Functionality is restored when using LC_API 3.2.1

**Comment by juanjp600** [comment]
Seems to be the same issue as #11

**Comment by MonAmiral** [comment]
I've uploaded a new version on Thunderstore, the mod works again with LC API 3.2.2, thank you juan!
