### ISSUE TITLE
I can see myself as a dog but other players cannot

### ISSUE THREAD

**Issue by Saithie** [MonAmiral/PlayerDogModel#11]
Hi there, 
Experiencing a problem that I can change myself into a dog, I can see that I am standing lower and with a camera mod - I can see that I am a dog. But other players cannot see myself as a dog.
Same goes with everyone else. Friends tested my mod profile and experience the same situation. 
Everything is updated and installed through Thunderstore app.
In BepInEx I can see the following: 
[Info   :   BepInEx] Loading [PlayerDogModel 1.0.2]
[Info   :PlayerDogModel] PlayerDogModel loaded
[Info   : Unity Log] Dog model is on the wrong shadow casting mode. (On instead of ShadowsOnly)

I added a .txt file of a full BepInEx log. 
[BepInEx log.txt](https://github.com/MonAmiral/PlayerDogModel/files/13799351/BepInEx.log.txt)

**Comment by SpeedyDoggo** [comment]
Does this get fixed if you use the previous LC_API? That was what my friends tried and it looks like that's the fix for now.

**Comment by Saithie** [comment]
> Does this get fixed if you use the previous LC_API? That was what my friends tried and it looks like that's the fix for now.

Which previous version would you recommend? I can see on Thunderstore there is 3.2.2, 3.2.1 and 3.2.0 versions and all uploaded on the same day.

**Comment by Kimelillo** [comment]
@MonAmiral , I have been trying many other versions from LC Api and from your mod, combined it and nothing work, I can see myself as a dog but not my friend, and my friend doesn't see the model too. I think that maybe is the version and the dogplayermodel mod need an update.

**Comment by MonAmiral** [comment]
If every new LC_API version breaks the mod I'm not going to repeatedly waste my time fixing the issue, you'll have to use the previous version if you can, sorry!
