### ISSUE TITLE
Request: Stat difference options?

### ISSUE THREAD

**Issue by nogsmcgogs** [MonAmiral/PlayerDogModel#14]
Hi! Just wanted to say, love your mod, I've been using it as long as I've been playing the game. I've had a lot of fun with it!

However, I noticed in the notes/concept art for this mod you mentioned that dog players have more stamina, more speed, but less health; I was wondering, could there be a version or an option to remove those differences? I would rather have the same stats as everyone else personally, especially as in my group I like to play defensive against monsters the most, and having less health makes it a bit harder, lol.

Thanks!

**Comment by MonAmiral** [comment]
Hi!
I'm glad you like the mod, I did not implement the stat changes in the mod, the only gameplay difference is you're shorter!
The design sheet was made by someone else, and it was enough trouble to make the whole mod work without having individual stats hehe
