### ISSUE TITLE
[Enhancement] Add more Playable models?

### ISSUE THREAD

**Issue by rusocop** [MonAmiral/PlayerDogModel#3]
Add more models with different traits (I'm definitely in if you need help for this mod and testing) like scooper (Wall-E alike machine? can pick up dead bodies without occupying slots), gym rat (bigger slots and max weight but slower), hacker (max slots at 2, deactivates turrets permanently through terminal, has bigger discounts) etc.

I mean these are only ideas, I'm down for helping out with some code. Could be a banger mod actually. Contact me on Discord paellarusa99 if you want

**Comment by MonAmiral** [comment]
Sorry, that's not planned! You're free to use the code to make your own version of the mod however!
