### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by TheMajesticSeal** [MonAmiral/PlayerDogModel#4]
I'm not sure if this was a one off thing. I have a few other mods installed which I can give you if needed. My memory usage kept steadily increasing with this mod installed 50 mb at a time till my usage was 20,000mb+
Happened a couple times even after restarting. 
Ill test if it happens to friends with the same mods.

**Comment by MonAmiral** [comment]
I fixed the issue in 0.2.1! Sorry for the inconvenience.
