### ISSUE TITLE
Do not see the dog model.

### ISSUE THREAD

**Issue by TheMajesticSeal** [MonAmiral/PlayerDogModel#5]
It seems like I cannot get the dog model to show.
I was able to see the dog model once with a certain friend.
The camera does change height but the model is not visible.

I've tried now with a bunch of other mods, and with just LCAPI & Bepin installed.
I tried with and without a mod manager.
Not sure what the issue is, or if its happening to you too

**Comment by MonAmiral** [comment]
Hi!

Do you mean you don't see yourself, or you don't see other players with the model? 
You're not supposed to see yourself, I haven't made a first person model (hands and stuff).

There should be no problem seeing it on other players especially with only LCAPI & Bepin, can you check the console (it opens automatically with Thunderstore mod manager, idk about other managers) and tell me if there are errors?

**Comment by TheMajesticSeal** [comment]
I dont see other players with the model.
![image](https://github.com/MonAmiral/PlayerDogModel/assets/10160896/4a9c10ce-0ca6-45d6-8e7c-db468b2c74b4)
Console just says this. BepIn 5.4.2100, LC 2.1.1.

I also tried on LC 1.4.0-2.1.0 since it says that's the preferred version and I cant even click the dog mask
Gives this error
![image](https://github.com/MonAmiral/PlayerDogModel/assets/10160896/34feb4ef-9a53-47d6-9397-94e9fa47ab70)

I was able to see my own dog ragdoll on death after testing today but that's about it.

**Comment by Doc94** [comment]
For my i added a mod for thrid person and cannot see the dog model.

**Comment by MonAmiral** [comment]
I'm adding more logs in the upcoming version to know more clearly what's going wrong, please let me know if it happens again!

**Comment by TheMajesticSeal** [comment]
![image](https://github.com/MonAmiral/PlayerDogModel/assets/10160896/1711a8b0-82dc-452b-a647-1a95d04357e1)

**Comment by MonAmiral** [comment]
This error message happens when someone switches model but the initialization of the model failed when they joined, there should be a more detailed log far above, right after they join the game (or when you join the game if they are hosting).

**Comment by TheMajesticSeal** [comment]
I have finally found the reason. Apparently having someone nicknamed on steam causes the dog model to not load for said player. Everyone I didn't have nicknamed the dog loaded fine. It just so happens that the people I was testing with were nicknamed.
Not sure how easy of a fix that would be lol.

**Comment by MonAmiral** [comment]
That's a very unique problem, I'm not sure I have the time to fix such a specific issue!
Could you reproduce the bug and provide the whole error log so I can look at it? It's located in C:\Users\your username\AppData\LocalLow\ZeekerssRBLX\Lethal Company\Player.log

**Comment by TheMajesticSeal** [comment]
[Player.log](https://github.com/MonAmiral/PlayerDogModel/files/13746545/Player.log)
Im not sure there is any errors in the log but yeah

**Comment by MonAmiral** [comment]
Indeed, there's no error or exception... Is this the log from a time where you played with someone with a nickname and the model didn't load?

**Comment by TheMajesticSeal** [comment]
Yup, just tested it 20 min ago. Its some sort of client side issue. Only the person who nicknamed the people cant see the dog model. So the model does load, its just not visible to the nicknamer.

**Comment by MonAmiral** [comment]
Thank you for your help and patience! I've finally located and fixed the issue in 1.0.2!
