### ISSUE TITLE
Making the helmets movable

### ISSUE THREAD

**Issue by Ardenos** [MonAmiral/PlayerDogModel#6]
Hello,

With the More Suits mods, my friends and I got too much skins for us to see the helmet so we had to remove some skins so we could click on it. Is there a way for you to make the helmets movable or to change its location since I think I'm not the only one who will have the same problem ?

Thanks!

**Comment by MonAmiral** [comment]
I'll consider it, would it work to just move the helmets to the other side of the suits rack?

**Comment by Ardenos** [comment]
I don't know, I don't think so since many mods could block the dog helmet, that's why I asked for movable helmet (if possible)

**Comment by MonAmiral** [comment]
Movable helmets is a lot more work and not planned, sorry!
