### ISSUE TITLE
Can't switch to dog

### ISSUE THREAD

**Issue by AleksanteriA** [MonAmiral/PlayerDogModel#7]
Hey!

I am trying this mod with BepinEx 5.4.2100
I can see the objects with "Switch model" but I get these errors when I try to switch.
![image](https://github.com/MonAmiral/PlayerDogModel/assets/60737700/07f50607-afe2-4b73-93e4-7e6c21a5fa42)

**Comment by SpeedyDoggo** [comment]
I had this issue before with an outdated version of LC API. Is yours on the right version for this mod? Lethal Company itself also updated, so what version are you running?

**Comment by AleksanteriA** [comment]
I have LC API 1.4 and I am running v 45 of Lethal company

**Comment by MonAmiral** [comment]
I've improved the logs to understand more clearly what is going wrong, please let me know if the issues persist with 0.3.2 and include the logs!

**Comment by AleksanteriA** [comment]
![image](https://github.com/MonAmiral/PlayerDogModel/assets/60737700/896b892e-d7ef-4083-9bd2-5273e406212a)
I get the same error
Are there any known mods that don't work with this?

**Comment by MonAmiral** [comment]
There are many mods which could cause this, what mods do you have installed?

**Comment by AleksanteriA** [comment]
![image](https://github.com/MonAmiral/PlayerDogModel/assets/60737700/797af33e-20e7-4403-b943-16c026b16012)
These

**Comment by MonAmiral** [comment]
I can't tell what all of these are but yeah it looks like one of them is probably causing the issue, does it keep causing errors when all mods but the dog (and BepInEx/LCAPI) are disabled?

**Comment by AleksanteriA** [comment]
![image](https://github.com/MonAmiral/PlayerDogModel/assets/60737700/6dd478c4-0bbd-4570-9c20-def4edadfe7b)
Errors look exactly the same when I have only these
However, it seems that without MoreSuits I can't even see the dog model in-game next to the suits rack

**Comment by MonAmiral** [comment]
The errors you're seeing are consequences of another error which happens when starting/joining a game, can you send me the whole game log so I can find what I'm looking for easily?
It's located in C:\Users\your username\AppData\LocalLow\ZeekerssRBLX\Lethal Company\Player.log

**Comment by AleksanteriA** [comment]
[Player.log](https://github.com/MonAmiral/PlayerDogModel/files/13732144/Player.log)
Here!

**Comment by MonAmiral** [comment]
Ah, there is an error when loading a game save which used to have MoreSuits but no longer has it, please do it again with a clean save!

**Comment by AleksanteriA** [comment]
[Player.log](https://github.com/MonAmiral/PlayerDogModel/files/13732188/Player.log)
Hmm, that fixed the problem of not seeing the model in-game but otherwise seems like same problem

**Comment by MonAmiral** [comment]
I think the problem might come from LC_API being version 1.0.0! Please update it to the latest version and let me know if it works.

**Comment by AleksanteriA** [comment]
Ayyy, thanks, it finally works! I hadn't tried that because on Thunderstore it suggest older one: "Preferred version: 1.4.0"
Anyways, awesome!

**Comment by MonAmiral** [comment]
No problem, thank you for your patience!
