### ISSUE TITLE
Dog Model Does Not Load

### ISSUE THREAD

**Issue by The-Tarkol** [MonAmiral/PlayerDogModel#9]
Very tragic error discovered today. Here's the stack trace.

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
PlayerDogModel.PlayerModelReplacer.UpdateMaterial () (at <c88129953fc8405c917f92384d2f2e39>:IL_0027)
PlayerDogModel.Plugin+UnlockableSuitPatch.SwitchSuitForPlayerPatch (GameNetcodeStuff.PlayerControllerB player, System.Int32 suitID, System.Boolean playAudio) (at <c88129953fc8405c917f92384d2f2e39>:IL_000F)
(wrapper dynamic-method) UnlockableSuit.DMD<UnlockableSuit::SwitchSuitForPlayer>(GameNetcodeStuff.PlayerControllerB,int,bool)
SuitSaver.Patches.Patches.LoadSuitFromFile () (at <cb8076e374694ce0a6eed9dab686c469>:IL_0045)
SuitSaver.Patches.Patches+EquipAfterSyncPatch+<LoadSuit>d__1.MoveNext () (at <cb8076e374694ce0a6eed9dab686c469>:IL_004B)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <e27997765c1848b09d8073e5d642717a>:IL_0026)

**Comment by MonAmiral** [comment]
This isn't enough information to find the source of the issue but I'm adding more logs in 0.3.2, if the problem persists please check the logs which should contain more precise information!
